baseURL = 'https://example.org/'
languageCode = 'en-us'
title = 'My New Hugo Site'
theme = 'docsy-0.10.0'
# in hugo.toml
[module]
  [[module.imports]]
    path = "github.com/kaushalmodi/hugo-fontawesome"
